MG_BLOCK_EDGE = 4
MG_BLOCK_BLOCK = 5
MG_BLOCK_TEXT = 8
MG_TEXT_TEXT = 4
SPACE_SENTENCE = 1
SPACE_PARAGRAPH = 1

ROW_SPLIT_MAX = 5
COL_SPLIT_MAX = 1
ROW_RATIO = 0.1 - 0.005
COL_RATIO = 0.1 - 0.005
MIN_AREA_PERCENT = 0.1
ROW_RATIO_CPN = 0.08
PX_PER_CHAR = 7
FONT_NORMAL = 13
FONT_TITLE = 18

IMAGE_WIDTH = 1000
IMAGE_HEIGHT = 1367

COLOR_BLOCK = (255, 128, 000)

DIR_TABLE_FIGURE = 'D:\Coding\DocumentLayoutGenerator\TableFigure\\'
OUT_DIR = "./output2/"
DATA_DIR = ""

